spring.application.name=conflict-tracker2

# Conexi�n a PostgreSQL en Render
spring.datasource.url=jdbc:postgresql://dpg-d7cok177f7vs738sp5o0-a.frankfurt-postgres.render.com:5432/conflict_tracker
spring.datasource.username=conflict_tracker_user
spring.datasource.password=tjK9Y8VXvLRM0KyzSuoeYBLcU4DHWT0C
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci�n JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Zona horaria opcional
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.sql.init.mode=always
spring.sql.init.platform=postgres

server.port=${PORT:8080}





