spring.application.name=conflict-tracker2

# Conexión a PostgreSQL en Render
spring.datasource.url=jdbc:postgresql://dpg-d64e2fpr0fns73c6iqgg-a.frankfurt-postgres.render.com:5432/example_postgresql_conflict
spring.datasource.username=example_postgresql_conflict_user
spring.datasource.password=Di9YdZHp0OZlOJt5B5ApVbpebxh4fK2g
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Zona horaria opcional
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.sql.init.mode=always
spring.sql.init.platform=postgres





